baseurl = "https://electrosenpai.github.io"
title = "Teaching"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true


[params]
author = "Jean-Baptiste DONNETTE"
info = "SRE, DevOps and teacher"
description = "Je vous souhaite la bienvenue sur mon blog dédié aux cours de mes étudiants ! Vous y trouverez des articles sur des sujets passionnants tels que l'introduction à la sécurité informatique, la programmation sur du cloud et l'architecture de services web. Que vous soyez débutant ou déjà expérimenté dans ces domaines, vous trouverez ici de précieuses informations pour approfondir vos connaissances et améliorer vos compétences. Je mets un point d'honneur à offrir des contenus de qualité, clairs et accessibles à tous."
license = '<a rel="license" href="https://creativecommons.org/licenses/by-nd/4.0/">CC BY-ND</a>'
keywords = "blog,developer,personal,teacher"
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5





[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/electrosenpai/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://fr.linkedin.com/in/jean-baptiste-donnette-83403587"


[languages.en]
languageName = ":gb:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Courses"
weight = 3
url = "courses/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.pt-fr]
languageName = ":fr:"
title = "Instituteur"

[languages.pt-fr.params]
author = "Jean-Baptiste DONNETTE"
info = "SRE, DevOps et Instituteur en école d'ingénieur"
description = "Je vous présente mes salutations et vous souhaite la bienvenue sur mon blog dédié aux cours de mes étudiants. Vous y trouverez des articles sur des sujets passionnants tels que l'introduction à la sécurité informatique, la programmation sur le cloud et l'architecture de services web. Que vous soyez débutant ou déjà expérimenté dans ces domaines, vous y découvrirez des informations précieuses pour approfondir vos connaissances et améliorer vos compétences. Je m'efforce de fournir des contenus de qualité, clairs et accessibles à tous. Je vous prie de bien vouloir explorer mon blog et de suivre mes actualités afin de ne rien manquer de mes derniers cours."
keywords = "blog,développeur,personnel,enseignant,académie"

[[languages.pt-fr.menu.main]]
name = "à-propos"
weight = 1
url = "about/"

[[languages.pt-fr.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.pt-fr.menu.main]]
name = "Mes Cours"
weight = 3
url = "courses/"

[[languages.pt-fr.menu.main]]
name = "Contact"
weight = 5
url = "contact/"
